baseurl = "https://carlosbecker.com/"
languageCode = "en-us"
title = "Carlos Alexandro Becker"
theme = "codex"
copyright = "Carlos Alexandro Becker - 2012 - {year}"

disableAliases = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "nord"
    noClasses = true
    tabWidth = 2

[related]
	threshold = 80
	includeNewer = true
	toLower = true

	[[related.indices]]
		name = "keywords"
		weight = 10

[permalinks]
	post = "/posts/:slug"

[privacy]
	[privacy.googleAnalytics]
		anonymizeIP = true
		respectDoNotTrack = true
		useSessionStorage = true
	[privacy.twitter]
		enableDNT = true
	[privacy.youtube]
		privacyEnhanced = true

[params]
	author = "Carlos Alexandro Becker"
	description = "Thoughts, rants and discoveries on software development and related stuff."
	keywords = "software development, software, golang, devops, go, sre, site reliability engineering"
	avatar = "avatar.jpg"
	twitter = "https://twitter.com/caarlos0"
	github = "https://github.com/caarlos0"
	email = "mailto:carlos@carlosbecker.dev?subject=Hi!"
	linkedin = "https://www.linkedin.com/in/caarlos0/"

[menu]
	[[menu.main]]
		identifier = "home"
		name = "Home"
		url = "/"
		weight = 10
	[[menu.main]]
		identifier = "posts"
		name = "Posts"
		url = "/posts/"
		weight = 20
	[[menu.main]]
		identifier = "talks"
		name = "Talks"
		url = "/talks/"
		weight = 30
	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/about/"
		weight = 40

[outputs]
home = [ "HTML", "RSS" ]
