baseurl = "https://carlosbecker.com/"
languageCode = "en-us"
title = "Carlos Alexandro Becker"
theme = "paper"
disqusShortname = "caarlos0blog"
googleAnalytics = "UA-50435491-1"
paginate = 5

pygmentsCodeFences = true
pygmentsStyle = "dracula"

[taxonomies]
	tag = "tags"

[related]
	threshold = 10
	includeNewer = true
	toLower = true

	[[related.indices]]
		name = "keywords"
		weight = 10

	[[related.indices]]
		name  = "tags"
		weight = 100

[permalinks]
	post = "/posts/:slug"

[privacy]
	[privacy.googleAnalytics]
		anonymizeIP = true
		respectDoNotTrack = true
		useSessionStorage = true
	[privacy.twitter]
		enableDNT = true
	[privacy.youtube]
		privacyEnhanced = true

[params]
	author = "Carlos Alexandro Becker"
	description = "Thoughts, rants and discoveries on software development and related stuff."
	keywords = "software development, software, golang, devops, go, sre, site reliability engineering"
	avatar = "avatar.jpg"

[menu]
	[[menu.main]]
		identifier = "archive"
		name = "Archive"
		url = "/archive/"
	[[menu.main]]
		identifier = "talks"
		name = "Talks"
		url = "/talks/"
	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/about/"
