baseurl = "https://carlosbecker.com/"
languageCode = "en-us"
title = "Carlos Alexandro Becker"
theme = "paper"
disqusShortname = "caarlos0blog"
googleAnalytics = "UA-50435491-1"
paginate = 5

disableAliases = true

pygmentsCodeFences = true
pygmentsStyle = "dracula"

[languages]
  [languages.en]
    weight = 2
  [languages.pt]
    weight = 1
    [languages.pt.menu]
      [[languages.pt.menu.main]]
        identifier = "archive"
        name = "Arquivo"
        url = "/archive/"
      [[languages.pt.menu.main]]
        identifier = "about"
        name = "Sobre"
        url = "/about/"

[taxonomies]
	tag = "tags"

[related]
	threshold = 80
	includeNewer = true
	toLower = true

	[[related.indices]]
		name = "keywords"
		weight = 10

	[[related.indices]]
		name = "tags"
		weight = 100

[permalinks]
	post = "/posts/:slug"

[privacy]
	[privacy.googleAnalytics]
		anonymizeIP = true
		respectDoNotTrack = true
		useSessionStorage = true
	[privacy.twitter]
		enableDNT = true
	[privacy.youtube]
		privacyEnhanced = true

[params]
	author = "Carlos Alexandro Becker"
	description = "Thoughts, rants and discoveries on software development and related stuff."
	keywords = "software development, software, golang, devops, go, sre, site reliability engineering"
	avatar = "avatar.jpg"

[menu]
	[[menu.main]]
		identifier = "archive"
		name = "Archive"
		url = "/archive/"
	[[menu.main]]
		identifier = "talks"
		name = "Talks"
		url = "/talks/"
	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/about/"

[outputs]
home = [ "HTML", "RSS", "REDIR", "HEADERS" ]

[mediaTypes]
	[mediaTypes."text/netlify"]
		suffixes = []
		delimiter = ""

[outputFormats]
	[outputFormats.REDIR]
		mediatype = "text/netlify"
		baseName = "_redirects"
		isPlainText = true
		notAlternative = true

	[outputFormats.HEADERS]
		mediatype = "text/netlify"
		baseName = "_headers"
		isPlainText = true
		notAlternative = true
