name: build

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: make setup avatar refresh ci
