name: build

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: 'recursive'
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: make setup ci
