name: refresh

on:
  push:
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: make setup avatar refresh ci
      - uses: stefanzweifel/git-auto-commit-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'docs: Update generated README'
          branch: master
